force-app/main/default/objects/Factura__c/Factura__c.object-meta.xml
<CustomObject>
    <label>Factura</label>
    <nameField>
        <label>Factura Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Facturas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Factura__c/fields/Pagada__c.field-meta.xml
<CustomField>
    <fullName>Pagada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pagada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/popUpHelper.cls
public with sharing class popUpHelper {
    @AuraEnabled(cacheable=true)
    public static List<Factura__c> getAccountList(string idObject) {
       
          list <Factura__c> factura = new list<Factura__c>();
         for (Factura__c fc  :[SELECT Pagada__c from Factura__c where Account__c =:idObject])  {
            factura.add(fc);
            
         }
         system.debug(factura);
        return factura;

    }
}