force-app/main/default/objects/Opportunity/fields/Fecha_de_Fin__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Fin__c</fullName>
    <label>Fecha de Fin</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Fecha_de_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Inicio__c</fullName>
    <label>Fecha de Inicio</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Servicio__c.field-meta.xml
<CustomField>
    <fullName>Servicio__c</fullName>
    <label>Servicio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Viaje Individual</fullName>
            </value>
            <value>
                <fullName>Alquiler de Vehiculo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Transport__c.field-meta.xml
<CustomField>
    <fullName>Transport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transport</label>
    <referenceTo>Transport__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Vehicle__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Transport__c/Transport__c.object-meta.xml
<CustomObject>
    <label>Transport</label>
    <nameField>
        <label>Transport Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/fechaDisponible.cls
public with sharing class fechaDisponible {
    public fechaDisponible() {


    }
    public static Boolean noDisponible(Opportunity aVerif){
        Boolean resp = false;
        List<Opportunity> getOpp = [SELECT Id, Name, StageName, Fecha_de_Fin__c, Fecha_de_Inicio__c, Servicio__c,Transport__c, Vehicle__c FROM Opportunity WHERE StageName ='Closed Won'];
        for(Opportunity verif : getOpp){
            if((verif.Fecha_de_Inicio__c <= aVerif.Fecha_de_Inicio__c && verif.Fecha_de_Fin__c >= aVerif.Fecha_de_Inicio__c)||
            (verif.Fecha_de_Inicio__c <= aVerif.Fecha_de_Fin__c && verif.Fecha_de_Fin__c >= aVerif.Fecha_de_Fin__c)){
                if ((verif.Servicio__c == 'Viaje Individual' && verif.Vehicle__c == aVerif.Vehicle__c )||
                (verif.Servicio__c =='Alquiler de Vehiculo' && verif.Transport__c == aVerif.Transport__c)) {
                    resp= true;
                }
            }
        }
        return resp;
    
    }
}